<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240220173451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $data = [
            [1, "PORRAZ OAXACA VICTOR ELOY"],
            [2, "TELLEZ ROMERO MANUEL"],
            [3, "CRESPO LOPEZ OMAR"],
            [3, "GARCIA MONTES JUAN RODOLFO"],
            [3, "TORRES CERON ALEJANDRO"],
            [3, "VILLAGOMEZ ESPINOSA ALEJANDRA MIREYA"],
            [3, "VITE ALARCON FRANCISCO ERNESTO"],
            [3, "BAÑOS LOZADA JOVANNI RICARDO"],
            [3, "BARRAGAN ANGELES ALBERTO"],
            [3, "BASULTO SOTO JOSE"],
            [3, "HERNANDEZ BAUTISTA ARISTEO FRANCISCO"],
            [2, "HERNANDEZ MUÑOZ GERARDO FRANCISCO"],
            [3, "MARTINEZ BAÑOS MARIO"],
            [3, "ORDAZ HERNANDEZ GERZON RIBAI"],
            [4, "MEJIA ANGELES LAMBERTO HUGO"],
            [4, "GUERRERO BAUTISTA ERIK"],
            [4, "MEJIA LOPEZ DANIEL MARTIN"],
            [4, "NAJERA URIBE JAIME"],
            [4, "RUIZ REYES ROSALIO"],
            [4, "CABRERA LEON FERNANDO"],
            [4, "GARCIA SERRANO RAUL ALFONSO"],
            [4, "LEON OROZCO PABLO"],
            [4, "MUÑOZ HERNANDEZ SALVADOR"],
            [4, "MURILLO MORALES JOSE TRINIDAD"],
            [4, "OLGUIN CRUZ CAROLINA"],
            [4, "PERALES MEJIA GABRIELA"],
            [4, "RIVERA VEGA JOSE LUIS"],
            [4, "RUIZ CORTES KARINA"],
            [4, "VAZQUEZ ANGELES JOSE MAXIMILIANO"],
            [5, "GOMEZ TELLEZ JAVIER"],
            [5, "BADILLO TREJO MARIA DE LOURDES"],
            [5, "HERNANDEZ HERNANDEZ JUAN"],
            [5, "MARCOS SOTO LUZ DEL CARMEN"],
            [5, "RAMIREZ ESTRADA BRUNO"],
            [5, "RIVERA HERNANDEZ MARIA DE LA LUZ JOAQUINA"],
            [5, "ANGELES AGUILAR MARIO JAHEN"],
            [5, "CANTELLAN MARTINEZ PASCUAL"],
            [5, "GUZMAN SERRANO GUADALUPE ARACELI"],
            [5, "VIVEROS REYES GENARO"],
            [5, "ESCORZA IBARRA JESUS MAXIMINO"],
            [6, "ISLAS ACOSTA LUCERO"],
            [6, "GUZMAN DOLORES NICHDALI"],
            [6, "JUAREZ NARANJO ENRIQUE"],
            [6, "LUGO VALENCIA MIGUEL ALBERTO"],
            [6, "GARCIA PATLAN ALEJANDRO"],
            [6, "GLEASON CALZADA MARLENE AYLEEN"],
            [6, "HERNANDEZ LOZADA GREGORIO"],
            [6, "MARTINEZ ORTIZ ERICK"],
            [6, "MARTINEZ SANCHEZ VICTOR"],
            [6, "MERCADO MERCADO JUVENAL"],
            [6, "VARGAS GONZALEZ JUVENAL"],
            [7, "RUIZ CASANAS MIGUEL ANGEL"],
            [7, "ISLAS RUIZ EDUARDO"],
            [7, "CHEQUER PADILLA FARITH"],
            [7, "DURAN OLVERA JUAN MANUEL"],
            [7, "LICONA FLORES JUAN MANUEL"],
            [7, "REYES PIÑA JOSE ANTONIO"],
            [7, "RICO NAVARRO SERGIO"],
            [7, "ROBLES CRUZ ANA MARIA"],
            [7, "ANGELES TENA ERICK ANTONIO"],
            [7, "AVILA LUQUEÑO JORGE"],
            [7, "CRUZ SILVA DELFINA"],
            [7, "DELGADO ANGELES ADONAY CESAREO"],
            [7, "ESTRADA VERA CHRISTOPHER ARTURO"],
            [7, "GONZALEZ MAY ARMANDO"],
            [7, "LOPEZ SOTO JUAN JOSE"],
            [7, "MIRANDA CAMACHO ADRIANA"],
            [7, "PEÑA RESENDIZ JUAN CARLOS"],
            [7, "SUAREZ ORTIZ JUAN GUILLERMO"],
            [7, "ZARAGOZA MUCIÑO EVELIA"],
            [8, "DAMIAN CHAVEZ MARIA CIRILA"],
            [8, "GUZMAN GRANILLO CATALINA"],
            [8, "LOPEZ HERNANDEZ MA. GUADALUPE"],
            [8, "SALGADO RODRIGUEZ AVELINA"],
            [8, "SEGURA CONSUE SHEILA YAZMIN"],
            [8, "SUMANO GARCIA MARIA ELENA"],
            [8, "CAZARES REYES JOEL"],
            [8, "GARCIA MERCADO JUANA ISABEL"],
            [8, "QUIJANO BELTRAN HECTOR"],
            [8, "SANCHEZ GUTIERREZ ANTONIO"],
            [8, "BARRON AGUILAR VICTOR"],
            [8, "CARRASCO ACOSTA JOHANANN"],
            [8, "CHAVEZ GARCIA MA DE LOURDES"],
            [8, "GARCIA GARCIA PABLO"],
            [8, "GOMEZ RESENDIZ JAIME"],
            [8, "GUERRERO GODINEZ ARTURO"],
            [8, "ORTIZ SAMPERIO EDUARDO"],
            [8, "PALOMARES PAREDES RAFAELA"],
            [8, "RAMIREZ GONZALEZ MARTIN"],
            [8, "REYES MIRANDA LUIS"],
            [8, "REYES VEGA JUAN CARLOS"],
            [8, "VENTURA CORTES MARIA CRISTINA"],
            [8, "VENTURA CORTES MARIA DEL CARMEN"],
            [8, "ALCANTARA HERNANDEZ FERNANDO"],
            [8, "AMBRIZ PALACIOS DEMETRIO"],
            [8, "AVILA MARTINEZ DELFINA"],
            [8, "AYALA BORJA MARIA DEL CARMEN"],
            [8, "BAUTISTA TAPIA JOSE CARMEN"],
            [8, "CRUZ ISLAS PORFIRIO RAFAEL"],
            [8, "ESCAMILLA HERNANDEZ JUAN JAVIER"],
            [8, "FLORES GRANADOS HORACIO RICARDO"],
            [8, "GARCIA NOBLE KARINA"],
            [8, "GUTIERREZ HERNANDEZ MARIA ADRIANA"],
            [8, "GUZMAN HERNANDEZ AMADOR AURELIO"],
            [8, "HERNANDEZ ESTRADA OSUE FRANCISCO"],
            [8, "HERNANDEZ MUEDANO ISAC"],
            [8, "JUAREZ DOMINGUEZ MANUEL"],
            [8, "LICONA FLORES ARMANDO"],
            [8, "LOPEZ AVILA MAURO"],
            [8, "MARTINEZ GARCIA EDGAR"],
            [8, "MARTINEZ HERRERA DORA MARIA"],
            [8, "MARTINEZ TAPIA LUCIANO"],
            [8, "MORALES VAZQUEZ JUAN DE LA CRUZ"],
            [8, "MUÑOZ HERNANDEZ FRANCISCO JAVIER"],
            [8, "MUÑOZ HERNANDEZ VICTOR HUGO"],
            [8, "NAVA ROMERO ENRIQUE"],
            [8, "OCAMPO GOMEZ LEOBARDO FERNANDO"],
            [8, "OLIVER JIMENEZ ALICIA"],
            [8, "OSORNO ESCAMILLA GUADALUPE ADEYANEIRA"],
            [8, "PARRA VALDEZ JOSE LUIS"],
            [8, "PEREZ LUNA FERNANDO"],
            [8, "RAMIREZ SAMPERIO GENARO ALFONSO"],
            [8, "RESENDIZ RAMOS ARIEL"],
            [8, "ROBLES CRUZ JUAN ENRIQUE"],
            [8, "ROMERO SIERRA MARCO ANTONIO"],
            [8, "RUIZ SERNA SILVIA"],
            [8, "VENTURA MENDOZA MARIA FELIX"],
            [9, "GONZALEZ DE LUCIO J. TRINIDAD JUAN"],
            [9, "JERONIMO ARROYO MIGUEL"],
            [9, "ROMERO HERNANDEZ JUAN MANUEL"],
            [9, "CERON VALENCIA EDGAR"],
            [9, "HERNANDEZ CASTRO VICTOR MANUEL"],
            [9, "HERRERA MORALES JUAN JOSE"],
            [9, "JUAREZ ENCISO ALMAQUIO"],
            [9, "MELO ACOSTA FERNANDO"],
            [9, "MONROY LOPEZ MARLENE"],
            [9, "SARABIA SARABIA DULCE MARIA"],
            [9, "ZAMARRIPA LAZCANO BERTHA"],
            [9, "AGUILAR NOVOA ADRIAN PAVEL"],
            [9, "BAUTISTA MARTINEZ JAVIER"],
            [9, "CRUZ MEJIA NOEMI"],
            [9, "GONZALEZ GOMEZ RAUL"],
            [9, "HERNANDEZ GONZALEZ JUAN"],
            [9, "HERNANDEZ OLVERA ANTONIA"],
            [9, "HERNANDEZ TAPIA MODESTO"],
            [9, "ISLAS MEJIA GERARDO JOSE ANTONIO"],
            [9, "ISLAS PEREZ JUANA"],
            [9, "ORTIZ ALCIBAR ROSENDO"],
            ["9", "RAMOS SONI ARACELI"],
            ["9", "SANCHEZ TREVIÑO FERNANDO"],
            ["10", "ANGELES BAÑOS JAIME"],
            ["10", "GUTIERREZ MUÑOZ JOSE ANGEL"],
            ["10", "HERNANDEZ PEÑA ERIK DE JESUS"],
            ["10", "MADARIAGA ESPINOLA MARIANA"],
            ["10", "MARTINEZ AVILA JOSE ISABEL"],
            ["10", "RODRIGUEZ HERNANDEZ JOSE JESUS"],
            ["10", "ZUÑIGA HERNANDEZ JOSE GREGORIO"],
            ["10", "CASTELAZO ISLAS ANDRES ALEJANDRO"],
            ["10", "CASTILLO AGUILAR EDUARDO"],
            ["10", "CONSUE PEREZ FRANCISCA"],
            ["10", "GARCIA GONZALEZ GENARO"],
            ["10", "GODINEZ MARTINEZ ROSALIO"],
            ["10", "GOMEZ OJEDA MARIA FRANCISCA TERESA"],
            ["10", "HERNANDEZ RESENDIZ JUAN CARLOS"],
            ["10", "JIMENEZ BARRAGAN JOSE MIGUEL"],
            ["10", "JIMENEZ HERNANDEZ MAXIMINO"],
            ["10", "LINARES RAMIREZ FELIPE DE JESUS"],
            ["10", "LUNA MONZALVO LORENZO"],
            ["10", "MARTINEZ BAÑOS JUAN"],
            ["10", "MORALES SIERRA MARCO ANTONIO"],
            ["10", "PAREDES CANO MA CRISTINA"],
            ["10", "ROQUE CABIEDES JOSE BERNARDO"],
            ["10", "SANCHEZ SANCHEZ AURELIO"],
            ["10", "TAPIA HERNANDEZ ANDRES"],
            ["10", "VALENCIA SANCHEZ HECTOR ISAIAS"],
            ["10", "VARGAS GOMEZ RICARDO"],
            ["10", "VAZQUEZ LOPEZ RAQUEL"],
            ["10", "VEGA PACHECO CRISTIAN ROEL"],
            ["11", "LANDAVERDE HERNANDEZ RODOLFO"],
            ["11", "MEJIA MUÑOZ BRIGETTE"],
            ["11", "ALARCON LARA FABIAN"],
            ["11", "ALPIZAR MARTINEZ ANTONIO DE JESUS"],
            ["11", "BADILLO CALLEJAS OSCAR"],
            ["11", "ESPINOSA ISLAS MARISOL"],
            ["11", "ROQUE CABIEDES AGUSTIN ADAN"],
            ["11", "SERRANO MONZALVO REY ANTONIO"],
            ["11", "LUNA SILVA KARINA"],
            ["12", "GUTIERREZ MARTINEZ PEDRO"],
            ["12", "LOPEZ LOPEZ JOSAFAT FERNANDO"],
            ["20", "CORTES RODRIGUEZ FRANCISCO"],
            ["12", "GUERRA SANCHEZ MARIA LUISA"],
            ["12", "HERNANDEZ BAUTISTA FELIPE"],
            ["12", "ISLAS CASOLCO GREGORIO JULIAN"],
            ["12", "MARTINEZ SOLIS ALBERTO"],
            ["12", "PEREZ HERNANDEZ ABRAHAM JACOB"],
            ["12", "RESENDIZ RODRIGUEZ ALBERTO"],
            ["12", "ROLDAN CANALES MATEO"],
            ["13", "ISLAS PONTAZA MISHELL HUMBERTO"],
            ["13", "MARTINEZ GUZMAN PAULA"],
            ["13", "PEREZ MORALES OSCAR"],
            ["13", "ACOSTA MARTINEZ CHRISTIAN"],
            ["13", "AGUILAR PERALTA CECILIO"],
            ["13", "BARRERA PEREZ ROCIO"],
            ["13", "BARRERA PEREZ SARA ANGELICA"],
            ["13", "BENITEZ HERNANDEZ ANTONIO"],
            ["13", "CANALES LOPEZ PAULINO JORGE"],
            ["13", "CASTRO MOYA FRANCISCO"],
            ["13", "CHAVARRIA MONTOYA HECTOR"],
            ["13", "CORTES AVILA ANTONIO"],
            ["13", "CRUZ ENRIQUEZ MARIA GUADALUPE"],
            ["13", "FUENTES MENESES ANSELMO"],
            ["6", "GALVEZ CHAVARRIA JORGE DE JESUS"],
            ["13", "GARCIA ARTEAGA MARICELA"],
            ["13", "GONZALEZ HERNANDEZ MARIA AMPARO"],
            ["13", "GONZALEZ PEREZ SANDRA IVETH"],
            ["13", "GRANILLO GUZMAN CRESENCIANO"],
            ["13", "HERNANDEZ GARCIA GUSTAVO"],
            ["13", "HERNANDEZ MOEDANO NURIA LORENA"],
            ["13", "IBARRA GUERRERO CYNTHIA JHOSELIN"],
            ["13", "ISLAS ARISTA EVA"],
            ["13", "JIMENEZ CHAVEZ JUAN"],
            ["13", "LEAL HUERTA RENE"],
            ["13", "LOPEZ CABRERA ANTONIO"],
            ["13", "LOPEZ ENSASTIGA YURIEL"],
            ["13", "LUGO MUÑOZ GABRIELA"],
            ["13", "LUNA LEON RAFAELA"],
            ["13", "MONTAÑO HERNANDEZ EDSON"],
            ["13", "MORALES ESPITIA BERTHA ANGELICA"],
            ["13", "QUINTERO HERNANDEZ GEORGINA"],
            ["13", "REYES PATRICIO LUIS"],
            ["13", "RODRIGUEZ LAZCANO JOSE ROMEO"],
            ["13", "SANCHEZ GARCIA VALENTIN"],
            ["13", "SANTIAGO NICOLAS MARIA ELENA"],
            ["13", "SOLIS GRANILLO JOSE DE JESUS"],
            ["13", "SOLIS MARTINEZ LEONARDA"],
            ["13", "TREJO CAMPOS MARIO OSCAR"],
            ["13", "TREJO CHANES ANDRES"],
            ["13", "VARGAS VARGAS MARTHA"],
            ["13", "VERGARA ORDAZ ANTONIO DE JESUS"],
            ["13", "VITE HERNANDEZ BALDEMAR"],
            ["13", "VIZZUETT MARTINEZ LOURDES GRACIELA"],
            ["13", "ZARATE CORTES CESAR"],
            ["9", "ROBLES FLORES PANFILO LUIS"],
            ["14", "GAUDENCIO RODRIGUEZ LEYVA"],
            ["15", "ELEIDE MORELOS RAMIREZ"],
            ["8", "ROCIO HERNANDEZ CANDIA"],
            ["16", "LUIS ADAN SANCHEZ HERNANDEZ"],
            ["17", "BONIFACIO TREJO CHAVEZ"],
            ["18", "VERÓNICA VÁZQUEZ AVENDAÑO"],
            ["18", "MARIA GUADALUPE DE LA CRUZ HERNANDEZ"],
            ["19", "MONICA ELIZABETH MENESES GOMEZ"],
            ["12", "JUANA MARIA CORTEZ MENESES"],
            ["5", "VICTOR DANIEL VELEZ NAIZIR"],
            ["16", "LUZ MARIA ABAD REYES"],
            ["20", "LUIS ANGEL MENDEZ SANCHEZ"],
            ["19", "JULIO CESAR HERNANDEZ ZENTENO"],
            ["7", "BADILLO CALLEJAS OSCAR"],
            ["6", "TELLEZ ALCANTARA IVAN"],
            ["8", "MARIA ADRIANA GUTIERREZ HERNANDEZ"],
            ["18", "ARTURO HERNANDEZ HERRERA"],
            ["18", "URIEL REYES OREA"],
            ["18", "EURIDICE ALONDRA ROJAS CELEDONIO"],
            ["5", "HERNANDEZ MUÑOZ ALEJANDRO"],
            ["19", "MOISES JACOBO ABUD OLIVER"],
            ["3", "YESENIA GRANADOS"],
            ["8", "MARIA DEL CARMEN AYALA BORJA"],
            ["20", "EDGAR ISLAS MARTINEZ"],
            ["20", "CORTES RODRIGUEZ FRANCISCO"],
            ["19", "EDGAR ANDRES MANZANO RESENDIZ"],
            ["7", "ANTONIO MARTINEZ BAÑOS"],
            ["18", "AMPARO LUGO MUÑOZ"],
            ["1", "LIC. LINDA BLANCAS ZERMEÑO"],
            [18, "ALEJANDRA MICHEL MENDOZA LUGO"],
            [18, "IVAN ISLAS BARRERA"],
            [18, "OSWALDO PONCE ARTEAGA"],
            [17, "C. JUAN DEL ANGEL ALARCON"],
            [4, "JULIO CESAR RAMIREZ CRUZ"],
            [18, "MAIBELY ESCALANTE TENORIO"],
            [20, "ENRIQUE HERNANDEZ QUIROZ"],
            [18, "GUADALUPE EVELYN ROMERO HERNANDEZ"],
            [4, "GERMAN RICO GOMEZ"],
            [4, "CARLOS ALBERTO TOVAR SANCHEZ"],
            [15, "MISAEL CORTES NAVARRO"],
            [18, "EMMANUEL SANTILLAN AGUILAR"],
            [20, "DAVID SANCHEZ CURIEL"],
            [18, "ALEJANDRA MOLINA DIAZ"],
            [18, "ANTONIA ESCALANTE MILLAN"],
            [18, "LEONOR SOTO MORALES"],
            [18, "JUAN ENRIQUE GONZALEZ PALOMARES"],
            [18, "BRENDA ROCIO OCHOA FLORES"],
            [18, "LISANDRO DAVID BAUTISTA ZUÑIGA"],
            [18, "RAUL MARTINEZ CASTILLO"],
            [18, "JUAN ANTONIO GODINEZ MARTINEZ"],
            [18, "GABRIELA CHAVEZ GARCIA"],
            [18, "ALEJANDRO AYALA GONZALEZ"],
            [10, "JOSE BERNARDO ROQUE CABIEDES"],
            [8, "MARIA ELENA SUMANO GARCIA"],
            [16, "EDUARDO MANUEL NOVELO BARRERA"],
            [17, "ZENEN MIGUEL LEON SANTOS"],
            [18, "BEATRIZ ZUÑIGA HERNANDEZ"],
            [18, "MARIA RAMOS GUTIERREZ"]
        ];
        
        for ($i=0; $i < sizeof($data); $i++) { 
            $personal = $data[$i];
            $this->addSql("INSERT INTO personal (id, nombre, ocupacion_id) VALUES ($i + 1 ,'$personal[1]', $personal[0])");
        }

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
    }
}
